name: Build and Check linting for preview release

on:
  workflow_call:
    inputs:
      publish-artifact:
        default: false
        required: false
        type: boolean
  workflow_dispatch:

jobs:
  build_check:
    steps:
      - name: Set Swap Space # Needed to fix OOM error in runner
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 8

      - name: Checkout repo and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install mold linker
        uses: rui314/setup-mold@v1

      - name: Rust Setup
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "nightly-2025-05-09"
          targets: "wasm32-unknown-unknown"
          components: "clippy,rustfmt"

      - uses: cargo-bins/cargo-binstall@main
      - name: cargo-leptos setup
        run: cargo binstall --no-confirm cargo-leptos --version 0.2.28

      - name: Cache rust dependencies and build output
        uses: Swatinem/rust-cache@v2

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install npm deps
        run: pnpm install

      - uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: protobuf-compiler pkg-config libssl-dev
          version: 1.0

      - name: lint check
        run: |
          objcopy --version
          # removing cargo fmt requirement as its buggy: https://github.com/rust-lang/cargo/issues/15506
          # cargo fmt --check
          cargo clippy --no-deps --all-features --release -- -Dwarnings

      - name: Build the Leptos project to output
        run: cargo leptos build --release --lib-features release-lib --bin-features release-bin
        env:
          LEPTOS_HASH_FILES: true
          # LEPTOS_TAILWIND_VERSION: v3.4.17
      - run: touch .empty
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        if: ${{ inputs.publish-artifact }}
        with:
          name: build
          path: |
            target/prod-release/hot-or-not-web-leptos-ssr
            target/prod-release/hash.txt
            target/site
            .empty

      - name: Find and display hash file
        run: |
          find . -name "hash.txt" -type f
      # - name: Tree files
      #   run: |
      #     tree
